services:

  postgres:
    image: postgres:16
    container_name: airfare_postgres

    environment:
      POSTGRES_DB: airfare_db
      POSTGRES_USER: airfare_user
      POSTGRES_PASSWORD: airfare_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: